### ISSUE TITLE
Access denied for user 'root'@'localhost' 

### ISSUE THREAD

**Issue by saguileran** [shogo82148/actions-setup-mysql#1188]
I am trying to use the action but after many attempts I am getting the following error:

```bash
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
I have tried with and without password. The workflow I am using is based on ubuntu and I am trying to enter to the database as follows:

```yml
- name: actions-setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.39.2 
      with:
        auto-start: true
        mysql-version: "9.0"
        root-password: "$123456789"
        user: "dba"
        password: "$123456789"
- name: CreateDatabase
  run: |
    mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS Universidad;'
```

Any idea what could it be?
