### ISSUE TITLE
Action failed with v1.15.0

### ISSUE THREAD

**Issue by strviola** [shogo82148/actions-setup-mysql#814]
Error log:

```
rails aborted!
LoadError: libmysqlclient.so.20: cannot open shared object file: No such file or directory - /home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.4/lib/mysql2/mysql2.so
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.4/lib/mysql2.rb:36:in `require'
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.4/lib/mysql2.rb:36:in `<top (required)>'
/home/runner/work/lfb/lfb/config/application.rb:17:in `<top (required)>'
/home/runner/work/lfb/lfb/Rakefile:4:in `require_relative'
/home/runner/work/lfb/lfb/Rakefile:4:in `<top (required)>'
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/command.rb:51:in `invoke'
/home/runner/work/lfb/lfb/vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

My action:

\* `env.MYSQL_VERSION` is `'5.7'`

```yml
name: Build rails execution context
runs:
  using: Composite
  steps:
    - name: Install MySQL ${{ env.MYSQL_VERSION }}
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: ${{ env.MYSQL_VERSION }}
        root-password: ${{ env.TEST_DATABASE_PASS }}
        my-cnf: |
          [mysqld]
          character-set-server=utf8mb4
          [client]
          default-character-set=utf8mb4
          # ...
    - name: Set up DB
      shell: bash
      run: bundle exec rails db:setup
```

Workaround: use previous version

```diff
   steps:
     - name: Install MySQL ${{ env.MYSQL_VERSION }}
-      uses: shogo82148/actions-setup-mysql@v1
+      uses: shogo82148/actions-setup-mysql@v1.14.1
```
