### ISSUE TITLE
Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

### ISSUE THREAD

**Issue by Melchyore** [shogo82148/actions-setup-mysql#842]
Hi,

I'm having an error every time in my workflow. I don't understand why since it works locally with Act. Can you help me, please?

```yml
     - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1.16.0
        with:
          auto-start: true
          distribution: 'mysql'
          mysql-version: '8.0'
          my-conf: |
            default-authentication-plugin=mysql_native_password
            sync_binlog=0
            innodb_doublewrite=OFF
            innodb-flush-log-at-trx-commit=0
            innodb-flush-method=nosync
          user: ${{ secrets.MYSQL_USER }}
          root-password: ${{ secrets.MYSQL_PASSWORD }}
          password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Create database
        run: mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DB_NAME }};'
```

```bash
Run mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test;'
Warning: ning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

**Comment by shogo82148** [comment]
actions-setup-mysql starts the MySQL server in a different path than usual to prevent conflicts with the pre-installed MySQL.
you can get installed MySQL path by `steps.mysql.outputs.base-dir`.

Example:

```yaml
  - id: mysql
    name: Setup MySQL
    uses: shogo82148/actions-setup-mysql@v1.16.0
    with:
      auto-start: true
      distribution: 'mysql'
      mysql-version: '8.0'
      # it is "my-cnf" not "my-conf"
      my-cnf: |
        default-authentication-plugin=mysql_native_password
        sync_binlog=0
        innodb_doublewrite=OFF
        innodb-flush-log-at-trx-commit=0
        innodb-flush-method=nosync
      user: ${{ secrets.MYSQL_USER }}
      root-password: ${{ secrets.MYSQL_PASSWORD }}
      password: ${{ secrets.MYSQL_PASSWORD }}

  - name: Create database
    run: mysql -uroot -proot --socket ${{ steps.mysql.outputs.base-dir }}/tmp/mysql.sock -e 'CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DB_NAME }};'
```
