### ISSUE TITLE
Action fails with empty string in multiline my.cnf

### ISSUE THREAD

**Issue by felixkempf** [shogo82148/actions-setup-mysql#882]
Hi. I tried adding `secure-file-priv = ''` to my.cnf, like so:

```yaml
    steps:
      - uses: actions/checkout@v3

      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: ${{ env.MYSQL_ROOT_PASSWORD }}
          my-cnf: |
            secure-file-priv = ''
            character-set-server = utf8mb4
            collation-server = utf8mb4_0900_ai_ci
            sql-mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
```

According to https://yaml-multiline.info/ that should be valid YAML.

But this yields 
<img width="869" alt="image" src="https://github.com/shogo82148/actions-setup-mysql/assets/8512231/f20ab5dd-4781-4e87-855e-a72fc4a1420b">

Moving the `secure-file-priv` line down to before the `sql-mode` line: 

```yaml
          my-cnf: |
            character-set-server = utf8mb4
            collation-server = utf8mb4_0900_ai_ci
            secure-file-priv = ''
            sql-mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
```

the error changes to 

> unexpected character "s"

so the unexpected character is the first character of the next line after the empty string. 

Changing the quotes to double quotes fails the same way.

Only when `secure-file-priv` is the very last line, it works as expected.

```yaml
          my-cnf: |
            character-set-server = utf8mb4
            collation-server = utf8mb4_0900_ai_ci
            sql-mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
            secure-file-priv = ''
```

So it must be the empty string causing trouble somehow.

runners are `ubuntu-20.04` btw.
